name: pytest on Windows
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  source_dir: grid_apps

jobs:
  pytest:
    name: pytest (Windows)
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        python_ver: ['3.10']
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1
      CONDA_CHANNEL_PRIORITY: strict
      PIP_NO_DEPS: 1 # all dependencies are installed from conda
      CONDA_LOCK_ENV_FILE: environments/py-${{ matrix.python_ver }}-win-64-dev.conda.lock.yml
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - name: Setup conda env
        uses: mamba-org/setup-micromamba@25b0505146bcbf25fc0b007ec3dbf0d16a592087
        with:
          environment-file: ${{ env.CONDA_LOCK_ENV_FILE }}
          environment-name: test_env
          init-shell: powershell
          cache-downloads: true
      - name: pytest
        run: pytest --cov --cov-report=xml
      - name: Codecov
        if: ${{ success() && matrix.python_ver == '3.10' }}
        uses: codecov/codecov-action@2f9a6e947d9f1025e3d1c427046f63693c71b52e
        with:
          name: GitHub
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
